import 'strokes.dart';

/// What can appear in a prompt or an answer tile.
///
/// Every subject — shape composition, counting, arithmetic, and later letters
/// and words — reduces to a row of figures. That keeps one renderer, one
/// staircase and one mastery pipeline serving all of them, instead of a
/// separate stack per subject.
///
/// Everything here is drawn from data, never generated by a model. A generated
/// picture of "seven mangoes" is sometimes six, and an item that teaches the
/// wrong count is worse than no item. Quantity, letter shape and composition
/// are correct by construction or they are not used.
sealed class Figure {
  const Figure();
}

/// A composed shape from the stroke vocabulary.
class ShapeFigure extends Figure {
  const ShapeFigure(this.shape);
  final Shape shape;
}

/// A counted group. Drawn as discrete marks so the count is always exact.
class QuantityFigure extends Figure {
  const QuantityFigure(this.count, {this.token = CountToken.dot});
  final int count;
  final CountToken token;
}

/// What the things being counted actually are.
///
/// A ten-frame of blue dots is a maths textbook. Five mangoes in the same frame
/// is a Wednesday at Muea market, and a child who has carried mangoes has
/// something to count *with* rather than an abstraction to count *about*.
///
/// The frame stays — it is what lets a child see five at a glance instead of
/// counting one by one, and that is the actual skill. Only the marks change.
/// Every item picks one token and uses it for every quantity on screen, because
/// comparing four mangoes to six footballs is a different, harder question than
/// the one being asked.
enum CountToken {
  dot,
  square,
  triangle,
  mango,
  ball,
  fish,
  leaf,
  star;

  /// The tokens that look like things. Kept apart from the plain marks so a
  /// shape question can still use a neutral dot.
  static const List<CountToken> things = [mango, ball, fish, leaf, star];
}

/// A written number.
class NumeralFigure extends Figure {
  const NumeralFigure(this.value);
  final int value;
}

/// Something to listen to.
///
/// Reading questions above the shape rungs ask about a *sound*, and a sound has
/// no appearance. Every one of them was drawing an empty dashed box: a child
/// looking at the placement probe saw two blank squares and four letters, with
/// no way to know what was being asked and no way to hear it again if the
/// moment passed. Five of the six reading forms did this, which is levels four
/// through ten — the entire part of reading that matters.
///
/// So a sound is now a thing on screen: a button that says it, and says it
/// again every time it is pressed. [phraseId] is a voice-catalogue id.
class SoundFigure extends Figure {
  const SoundFigure(this.phraseId);
  final String phraseId;
}

/// A picture of a word.
///
/// Where the thing being asked about can be drawn, it is drawn — a child
/// picking which written word says *bus* should be looking at a bus, not at a
/// blank box waiting for audio they may already have missed.
class PictureFigure extends Figure {
  const PictureFigure(this.word);
  final String word;
}

/// A single letter, upper or lower case.
class LetterFigure extends Figure {
  const LetterFigure(this.letter);
  final String letter;
}

/// A whole written word. The thing a child is learning to read.
/// A written word.
///
/// [withPicture] decides whether its drawing is shown above the letters, and
/// the default is on because most places a word appears it is there to be
/// *understood* — the picture carries the meaning while the letters carry the
/// reading.
///
/// It must be turned off wherever the word is the thing being read. Four word
/// tiles that each carry their own picture can be told apart by the pictures
/// alone, so a child hears "bed", finds the bed drawing, and never looks at a
/// letter. The rung then measures vocabulary, not decoding, while the graph
/// goes on claiming otherwise.
class WordFigure extends Figure {
  const WordFigure(this.word, {this.withPicture = true});
  final String word;
  final bool withPicture;
}

/// An operator or placeholder drawn as strokes, so a prompt row contains no
/// type a child would have to read.
class SymbolFigure extends Figure {
  const SymbolFigure(this.symbol);
  final MathSymbol symbol;
}

/// Two pictured things joined by a word — "cat on mat" as a miniature scene.
///
/// Understanding a sentence means knowing which situation it describes, and
/// a single object drawing cannot show a situation. This composes two drawings
/// the child already knows with the joiner between them, the same way
/// [decode.sentence] got past the artwork wall by changing the interaction
/// rather than commissioning new pictures.
class PhraseFigure extends Figure {
  const PhraseFigure(this.first, this.joiner, this.second);

  /// The subject — what the sentence is about.
  final String first;

  /// The link word, spoken aloud but drawn small: on, in, sur.
  final String joiner;

  /// The other thing — where, or what it is in.
  final String second;

  @override
  bool operator ==(Object other) =>
      other is PhraseFigure &&
      other.first == first &&
      other.joiner == joiner &&
      other.second == second;

  @override
  int get hashCode => Object.hash(first, joiner, second);
}

enum MathSymbol { plus, minus, equals, unknown, greater, less }

/// How a child answers. Tapping one of four is the floor, not the ceiling.
enum Interaction {
  /// Choose one option.
  choose,

  /// Build the answer in order from a pool of letters — spelling.
  spell,

  /// Say it back. Always optional, never scored: see SayItBack for why.
  speak,

  /// Join each thing on the left to its partner on the right.
  ///
  /// Choosing one of four tests recognition. Matching a whole set tests the
  /// relationship itself — four is more than three, this quantity *is* that
  /// numeral — and it cannot be guessed the way a single choice can.
  match,

  /// Drag a row of things into the right sequence.
  ///
  /// Ordinality, which is a different thing from the comparison rung and is
  /// not reachable by choosing: "which is bigger" is one pairwise judgement,
  /// while putting four quantities in order means holding the whole sequence
  /// in mind at once. It is also the first interaction where a child moves
  /// something rather than pointing at it.
  order,
}

/// A single question, in the one shape the session knows how to render.
class PrimarItem {
  const PrimarItem({
    required this.id,
    required this.level,
    required this.topicId,
    required this.prompt,
    required this.options,
    required this.answerIndex,
    this.spoken,
    this.spokenAll = const [],
    this.teach = const [],
    this.interaction = Interaction.choose,
    this.spellTarget = const [],
    this.spellPool = const [],
    this.matchLeft = const [],
    this.matchRight = const [],
    this.matchPairing = const [],
    this.orderItems = const [],
    this.orderSolution = const [],
    this.sayTarget,
  });

  final String id;
  final int level;

  /// Matches curriculum_nodes.topic_id, so mastery lands on the right node.
  final String topicId;

  /// The question row, read left to right.
  final List<Figure> prompt;
  final List<Figure> options;
  final int answerIndex;

  /// Several lines spoken in order as the prompt, where one is not enough.
  ///
  /// Blending is the reason this exists: the question *is* a sequence — /k/
  /// /a/ /t/ — and a single `spoken` line cannot express it. Empty everywhere
  /// else, and [spoken] remains the single-line case so nothing already
  /// working had to change.
  final List<String> spokenAll;

  /// How this item is answered.
  final Interaction interaction;

  /// For [Interaction.spell]: the letters, in order, that build the answer.
  final List<String> spellTarget;

  /// For [Interaction.spell]: the tiles offered, answer letters plus decoys.
  final List<String> spellPool;

  /// For [Interaction.match]: the left column.
  final List<Figure> matchLeft;

  /// For [Interaction.match]: the right column, shuffled. Index i on the left
  /// belongs with [matchPairing]\[i] on the right.
  final List<Figure> matchRight;

  /// For [Interaction.match]: which right-hand item each left-hand one belongs
  /// with.
  final List<int> matchPairing;

  /// For [Interaction.order]: the tiles as the child first sees them, already
  /// shuffled. Never in the solved order — a question that starts answered
  /// teaches nothing and scores as a success.
  final List<Figure> orderItems;

  /// For [Interaction.order]: the indices of [orderItems] in the order they
  /// belong. `[2, 0, 1]` means the third tile shown goes first.
  final List<int> orderSolution;

  /// What the child could say aloud after getting this right, if anything.
  ///
  /// Null on items where speaking would be meaningless — there is nothing to
  /// say back about a shape composition, and asking would be noise. Where it is
  /// set it is the plain word, not a phrase id: it is matched against what a
  /// recogniser heard, never spoken by the app.
  ///
  /// Speaking is **always** optional and **only ever** earns a reward. See
  /// [SayItBack] for why a misheard child must never be marked down.
  final String? sayTarget;

  /// Phrase id spoken when the item appears — the question.
  final String? spoken;

  /// What the companion says when a child misses.
  ///
  /// Not "wrong", and not merely "this one". A miss is the moment a child is
  /// most ready to be taught, so the answer is named and explained: the letter
  /// and the sound it makes, the count spoken aloud, the total reached. An app
  /// that only ever marks answers is a test, not a lesson.
  final List<String> teach;

  /// Whether the prompt row has anything worth drawing a sheet around.
  ///
  /// Symbols alone do not count. The comparison form's prompt is a single "»"
  /// and the match board's was a single "=", each rendered as a wide band of
  /// blank paper with one glyph floating in it — a mark most six-year-olds
  /// cannot read, above the tiles that are the actual question.
  ///
  /// The symbols stay in the data because the misconception classifier reads
  /// them to tell a comparison from a sum. They simply do not earn a sheet.
  bool get hasVisiblePrompt => prompt.any((f) => f is! SymbolFigure);

  Figure get answer => options[answerIndex];
}
