// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1UWKHuEPDn81zVjS3zVmfeuLiz2-Sy0g',
    appId: '1:613507205446:web:4273277c53d8416313fd47',
    messagingSenderId: '613507205446',
    projectId: 'operating-axis-420213',
    authDomain: 'operating-axis-420213.firebaseapp.com',
    storageBucket: 'operating-axis-420213.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfLopHRc7cnW-mEqto1CtiwIEk34qGWi4',
    appId: '1:613507205446:android:73e9d18897fff00313fd47',
    messagingSenderId: '613507205446',
    projectId: 'operating-axis-420213',
    storageBucket: 'operating-axis-420213.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn8lnKv4fF-JNKJ8UVe6G1_b3qfwGqKto',
    appId: '1:613507205446:ios:467d806bf32927ac13fd47',
    messagingSenderId: '613507205446',
    projectId: 'operating-axis-420213',
    storageBucket: 'operating-axis-420213.firebasestorage.app',
    iosBundleId: 'com.prepskul.prepskul',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn8lnKv4fF-JNKJ8UVe6G1_b3qfwGqKto',
    appId: '1:613507205446:ios:467d806bf32927ac13fd47',
    messagingSenderId: '613507205446',
    projectId: 'operating-axis-420213',
    storageBucket: 'operating-axis-420213.firebasestorage.app',
    iosBundleId: 'com.prepskul.prepskul',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1UWKHuEPDn81zVjS3zVmfeuLiz2-Sy0g',
    appId: '1:613507205446:web:bf8b9fb5c1230cb913fd47',
    messagingSenderId: '613507205446',
    projectId: 'operating-axis-420213',
    authDomain: 'operating-axis-420213.firebaseapp.com',
    storageBucket: 'operating-axis-420213.firebasestorage.app',
  );
}