import 'package:prepskul/core/models/phone_country.dart';

/// Comprehensive dial-code list (Cameroon first, then alphabetical).
const List<PhoneCountry> kPhoneCountries = [
  PhoneCountry.cameroon,
  PhoneCountry(name: 'Afghanistan', isoCode: 'AF', dialCode: '+93', flag: '🇦🇫'),
  PhoneCountry(name: 'Albania', isoCode: 'AL', dialCode: '+355', flag: '🇦🇱'),
  PhoneCountry(name: 'Algeria', isoCode: 'DZ', dialCode: '+213', flag: '🇩🇿'),
  PhoneCountry(name: 'Angola', isoCode: 'AO', dialCode: '+244', flag: '🇦🇴'),
  PhoneCountry(name: 'Argentina', isoCode: 'AR', dialCode: '+54', flag: '🇦🇷'),
  PhoneCountry(name: 'Australia', isoCode: 'AU', dialCode: '+61', flag: '🇦🇺'),
  PhoneCountry(name: 'Austria', isoCode: 'AT', dialCode: '+43', flag: '🇦🇹'),
  PhoneCountry(name: 'Bahrain', isoCode: 'BH', dialCode: '+973', flag: '🇧🇭'),
  PhoneCountry(name: 'Bangladesh', isoCode: 'BD', dialCode: '+880', flag: '🇧🇩'),
  PhoneCountry(name: 'Belgium', isoCode: 'BE', dialCode: '+32', flag: '🇧🇪'),
  PhoneCountry(name: 'Benin', isoCode: 'BJ', dialCode: '+229', flag: '🇧🇯'),
  PhoneCountry(name: 'Botswana', isoCode: 'BW', dialCode: '+267', flag: '🇧🇼'),
  PhoneCountry(name: 'Brazil', isoCode: 'BR', dialCode: '+55', flag: '🇧🇷'),
  PhoneCountry(name: 'Burkina Faso', isoCode: 'BF', dialCode: '+226', flag: '🇧🇫'),
  PhoneCountry(name: 'Burundi', isoCode: 'BI', dialCode: '+257', flag: '🇧🇮'),
  PhoneCountry(name: 'Cambodia', isoCode: 'KH', dialCode: '+855', flag: '🇰🇭'),
  PhoneCountry(name: 'Canada', isoCode: 'CA', dialCode: '+1', flag: '🇨🇦'),
  PhoneCountry(name: 'Central African Republic', isoCode: 'CF', dialCode: '+236', flag: '🇨🇫'),
  PhoneCountry(name: 'Chad', isoCode: 'TD', dialCode: '+235', flag: '🇹🇩'),
  PhoneCountry(name: 'Chile', isoCode: 'CL', dialCode: '+56', flag: '🇨🇱'),
  PhoneCountry(name: 'China', isoCode: 'CN', dialCode: '+86', flag: '🇨🇳'),
  PhoneCountry(name: 'Colombia', isoCode: 'CO', dialCode: '+57', flag: '🇨🇴'),
  PhoneCountry(name: 'Congo', isoCode: 'CG', dialCode: '+242', flag: '🇨🇬'),
  PhoneCountry(name: 'DR Congo', isoCode: 'CD', dialCode: '+243', flag: '🇨🇩'),
  PhoneCountry(name: 'Côte d\'Ivoire', isoCode: 'CI', dialCode: '+225', flag: '🇨🇮'),
  PhoneCountry(name: 'Croatia', isoCode: 'HR', dialCode: '+385', flag: '🇭🇷'),
  PhoneCountry(name: 'Cyprus', isoCode: 'CY', dialCode: '+357', flag: '🇨🇾'),
  PhoneCountry(name: 'Czech Republic', isoCode: 'CZ', dialCode: '+420', flag: '🇨🇿'),
  PhoneCountry(name: 'Denmark', isoCode: 'DK', dialCode: '+45', flag: '🇩🇰'),
  PhoneCountry(name: 'Djibouti', isoCode: 'DJ', dialCode: '+253', flag: '🇩🇯'),
  PhoneCountry(name: 'Egypt', isoCode: 'EG', dialCode: '+20', flag: '🇪🇬'),
  PhoneCountry(name: 'Equatorial Guinea', isoCode: 'GQ', dialCode: '+240', flag: '🇬🇶'),
  PhoneCountry(name: 'Eritrea', isoCode: 'ER', dialCode: '+291', flag: '🇪🇷'),
  PhoneCountry(name: 'Estonia', isoCode: 'EE', dialCode: '+372', flag: '🇪🇪'),
  PhoneCountry(name: 'Ethiopia', isoCode: 'ET', dialCode: '+251', flag: '🇪🇹'),
  PhoneCountry(name: 'Finland', isoCode: 'FI', dialCode: '+358', flag: '🇫🇮'),
  PhoneCountry(name: 'France', isoCode: 'FR', dialCode: '+33', flag: '🇫🇷'),
  PhoneCountry(name: 'Gabon', isoCode: 'GA', dialCode: '+241', flag: '🇬🇦'),
  PhoneCountry(name: 'Gambia', isoCode: 'GM', dialCode: '+220', flag: '🇬🇲'),
  PhoneCountry(name: 'Germany', isoCode: 'DE', dialCode: '+49', flag: '🇩🇪'),
  PhoneCountry(name: 'Ghana', isoCode: 'GH', dialCode: '+233', flag: '🇬🇭'),
  PhoneCountry(name: 'Greece', isoCode: 'GR', dialCode: '+30', flag: '🇬🇷'),
  PhoneCountry(name: 'Guinea', isoCode: 'GN', dialCode: '+224', flag: '🇬🇳'),
  PhoneCountry(name: 'Hong Kong', isoCode: 'HK', dialCode: '+852', flag: '🇭🇰'),
  PhoneCountry(name: 'Hungary', isoCode: 'HU', dialCode: '+36', flag: '🇭🇺'),
  PhoneCountry(name: 'India', isoCode: 'IN', dialCode: '+91', flag: '🇮🇳'),
  PhoneCountry(name: 'Indonesia', isoCode: 'ID', dialCode: '+62', flag: '🇮🇩'),
  PhoneCountry(name: 'Iran', isoCode: 'IR', dialCode: '+98', flag: '🇮🇷'),
  PhoneCountry(name: 'Iraq', isoCode: 'IQ', dialCode: '+964', flag: '🇮🇶'),
  PhoneCountry(name: 'Ireland', isoCode: 'IE', dialCode: '+353', flag: '🇮🇪'),
  PhoneCountry(name: 'Israel', isoCode: 'IL', dialCode: '+972', flag: '🇮🇱'),
  PhoneCountry(name: 'Italy', isoCode: 'IT', dialCode: '+39', flag: '🇮🇹'),
  PhoneCountry(name: 'Japan', isoCode: 'JP', dialCode: '+81', flag: '🇯🇵'),
  PhoneCountry(name: 'Jordan', isoCode: 'JO', dialCode: '+962', flag: '🇯🇴'),
  PhoneCountry(name: 'Kenya', isoCode: 'KE', dialCode: '+254', flag: '🇰🇪'),
  PhoneCountry(name: 'Kuwait', isoCode: 'KW', dialCode: '+965', flag: '🇰🇼'),
  PhoneCountry(name: 'Lebanon', isoCode: 'LB', dialCode: '+961', flag: '🇱🇧'),
  PhoneCountry(name: 'Liberia', isoCode: 'LR', dialCode: '+231', flag: '🇱🇷'),
  PhoneCountry(name: 'Libya', isoCode: 'LY', dialCode: '+218', flag: '🇱🇾'),
  PhoneCountry(name: 'Luxembourg', isoCode: 'LU', dialCode: '+352', flag: '🇱🇺'),
  PhoneCountry(name: 'Madagascar', isoCode: 'MG', dialCode: '+261', flag: '🇲🇬'),
  PhoneCountry(name: 'Malawi', isoCode: 'MW', dialCode: '+265', flag: '🇲🇼'),
  PhoneCountry(name: 'Malaysia', isoCode: 'MY', dialCode: '+60', flag: '🇲🇾'),
  PhoneCountry(name: 'Mali', isoCode: 'ML', dialCode: '+223', flag: '🇲🇱'),
  PhoneCountry(name: 'Mauritania', isoCode: 'MR', dialCode: '+222', flag: '🇲🇷'),
  PhoneCountry(name: 'Mauritius', isoCode: 'MU', dialCode: '+230', flag: '🇲🇺'),
  PhoneCountry(name: 'Mexico', isoCode: 'MX', dialCode: '+52', flag: '🇲🇽'),
  PhoneCountry(name: 'Morocco', isoCode: 'MA', dialCode: '+212', flag: '🇲🇦'),
  PhoneCountry(name: 'Mozambique', isoCode: 'MZ', dialCode: '+258', flag: '🇲🇿'),
  PhoneCountry(name: 'Namibia', isoCode: 'NA', dialCode: '+264', flag: '🇳🇦'),
  PhoneCountry(name: 'Nepal', isoCode: 'NP', dialCode: '+977', flag: '🇳🇵'),
  PhoneCountry(name: 'Netherlands', isoCode: 'NL', dialCode: '+31', flag: '🇳🇱'),
  PhoneCountry(name: 'New Zealand', isoCode: 'NZ', dialCode: '+64', flag: '🇳🇿'),
  PhoneCountry(name: 'Niger', isoCode: 'NE', dialCode: '+227', flag: '🇳🇪'),
  PhoneCountry(name: 'Nigeria', isoCode: 'NG', dialCode: '+234', flag: '🇳🇬'),
  PhoneCountry(name: 'Norway', isoCode: 'NO', dialCode: '+47', flag: '🇳🇴'),
  PhoneCountry(name: 'Oman', isoCode: 'OM', dialCode: '+968', flag: '🇴🇲'),
  PhoneCountry(name: 'Pakistan', isoCode: 'PK', dialCode: '+92', flag: '🇵🇰'),
  PhoneCountry(name: 'Palestine', isoCode: 'PS', dialCode: '+970', flag: '🇵🇸'),
  PhoneCountry(name: 'Peru', isoCode: 'PE', dialCode: '+51', flag: '🇵🇪'),
  PhoneCountry(name: 'Philippines', isoCode: 'PH', dialCode: '+63', flag: '🇵🇭'),
  PhoneCountry(name: 'Poland', isoCode: 'PL', dialCode: '+48', flag: '🇵🇱'),
  PhoneCountry(name: 'Portugal', isoCode: 'PT', dialCode: '+351', flag: '🇵🇹'),
  PhoneCountry(name: 'Qatar', isoCode: 'QA', dialCode: '+974', flag: '🇶🇦'),
  PhoneCountry(name: 'Romania', isoCode: 'RO', dialCode: '+40', flag: '🇷🇴'),
  PhoneCountry(name: 'Russia', isoCode: 'RU', dialCode: '+7', flag: '🇷🇺'),
  PhoneCountry(name: 'Rwanda', isoCode: 'RW', dialCode: '+250', flag: '🇷🇼'),
  PhoneCountry(name: 'Saudi Arabia', isoCode: 'SA', dialCode: '+966', flag: '🇸🇦'),
  PhoneCountry(name: 'Senegal', isoCode: 'SN', dialCode: '+221', flag: '🇸🇳'),
  PhoneCountry(name: 'Serbia', isoCode: 'RS', dialCode: '+381', flag: '🇷🇸'),
  PhoneCountry(name: 'Sierra Leone', isoCode: 'SL', dialCode: '+232', flag: '🇸🇱'),
  PhoneCountry(name: 'Singapore', isoCode: 'SG', dialCode: '+65', flag: '🇸🇬'),
  PhoneCountry(name: 'Somalia', isoCode: 'SO', dialCode: '+252', flag: '🇸🇴'),
  PhoneCountry(name: 'South Africa', isoCode: 'ZA', dialCode: '+27', flag: '🇿🇦'),
  PhoneCountry(name: 'South Korea', isoCode: 'KR', dialCode: '+82', flag: '🇰🇷'),
  PhoneCountry(name: 'South Sudan', isoCode: 'SS', dialCode: '+211', flag: '🇸🇸'),
  PhoneCountry(name: 'Spain', isoCode: 'ES', dialCode: '+34', flag: '🇪🇸'),
  PhoneCountry(name: 'Sri Lanka', isoCode: 'LK', dialCode: '+94', flag: '🇱🇰'),
  PhoneCountry(name: 'Sudan', isoCode: 'SD', dialCode: '+249', flag: '🇸🇩'),
  PhoneCountry(name: 'Sweden', isoCode: 'SE', dialCode: '+46', flag: '🇸🇪'),
  PhoneCountry(name: 'Switzerland', isoCode: 'CH', dialCode: '+41', flag: '🇨🇭'),
  PhoneCountry(name: 'Syria', isoCode: 'SY', dialCode: '+963', flag: '🇸🇾'),
  PhoneCountry(name: 'Taiwan', isoCode: 'TW', dialCode: '+886', flag: '🇹🇼'),
  PhoneCountry(name: 'Tanzania', isoCode: 'TZ', dialCode: '+255', flag: '🇹🇿'),
  PhoneCountry(name: 'Thailand', isoCode: 'TH', dialCode: '+66', flag: '🇹🇭'),
  PhoneCountry(name: 'Togo', isoCode: 'TG', dialCode: '+228', flag: '🇹🇬'),
  PhoneCountry(name: 'Tunisia', isoCode: 'TN', dialCode: '+216', flag: '🇹🇳'),
  PhoneCountry(name: 'Turkey', isoCode: 'TR', dialCode: '+90', flag: '🇹🇷'),
  PhoneCountry(name: 'Uganda', isoCode: 'UG', dialCode: '+256', flag: '🇺🇬'),
  PhoneCountry(name: 'Ukraine', isoCode: 'UA', dialCode: '+380', flag: '🇺🇦'),
  PhoneCountry(name: 'United Arab Emirates', isoCode: 'AE', dialCode: '+971', flag: '🇦🇪'),
  PhoneCountry(name: 'United Kingdom', isoCode: 'GB', dialCode: '+44', flag: '🇬🇧'),
  PhoneCountry(name: 'United States', isoCode: 'US', dialCode: '+1', flag: '🇺🇸'),
  PhoneCountry(name: 'Vietnam', isoCode: 'VN', dialCode: '+84', flag: '🇻🇳'),
  PhoneCountry(name: 'Yemen', isoCode: 'YE', dialCode: '+967', flag: '🇾🇪'),
  PhoneCountry(name: 'Zambia', isoCode: 'ZM', dialCode: '+260', flag: '🇿🇲'),
  PhoneCountry(name: 'Zimbabwe', isoCode: 'ZW', dialCode: '+263', flag: '🇿🇼'),
];
