import 'package:prepskul/core/services/log_service.dart';
import 'package:prepskul/core/services/storage_service.dart';
import 'package:prepskul/core/services/supabase_service.dart';

import '../l10n/skulmate_copy.dart';
import '../models/skulmate_intake_analysis.dart';
import '../models/skulmate_intake_models.dart';
import 'skulmate_service.dart';

/// Reads learner content and produces a topic brief for the intake chat.
class SkulMateIntakeAnalysisService {
  SkulMateIntakeAnalysisService._();

  static SkulMateIntakeAttachment previewAttachment(
    SkulMateIntakePayload payload,
    SkulMateCopy copy,
  ) =>
      _attachmentFor(payload, copy);

  static Future<SkulMateIntakeAnalysis> analyze(
    SkulMateIntakePayload payload, {
    required SkulMateCopy copy,
  }) async {
    final attachment = _attachmentFor(payload, copy);
    String? resolvedText = payload.text?.trim();
    String topicLabel;
    String? contextSummary;
    List<String>? uploadedFileUrls;
    List<String>? uploadedFileNames;
  SkulMateIntakeAttachment resolvedAttachment = attachment;

    if (payload.hasYoutube) {
      LogService.info('🎮 [skulMate] Analyzing YouTube intake…');
      try {
        resolvedText = await SkulMateService.resolveYoutubeTranscript(
          payload.youtubeUrl!,
        );
        topicLabel = _topicFromText(resolvedText) ??
            copy.intakeTopicFallbackYoutube;
      } catch (e) {
        // Captions are optional for intake preview — /generate can fetch server-side.
        LogService.warning(
          '🎮 [skulMate] YouTube caption preview skipped: $e',
        );
        topicLabel = copy.intakeTopicFallbackYoutube;
        resolvedText = null;
      }
    } else if (payload.hasText) {
      resolvedText = payload.text!.trim();
      topicLabel = _topicFromText(resolvedText) ??
          payload.title?.trim() ??
          copy.intakeTopicFallbackNotes;
    } else if (payload.hasTopicOnly) {
      topicLabel = payload.topicHint!.trim();
      resolvedText = null;
    } else if (payload.source == SkulMateIntakeSource.lecture) {
      topicLabel = payload.title?.trim() ??
          _topicFromText(resolvedText) ??
          copy.intakeTopicFallbackLecture;
    } else if (payload.hasImages) {
      final photoResult = await _analyzePhotoBundle(payload, copy);
      topicLabel = photoResult.topicLabel;
      contextSummary = photoResult.contextSummary;
      uploadedFileUrls = photoResult.uploadedFileUrls;
      uploadedFileNames = photoResult.uploadedFileNames;
      resolvedAttachment = photoResult.attachment;
    } else if (payload.hasFiles) {
      final cleaned = _cleanFileName(_fileName(payload));
      topicLabel = (cleaned != null && !_isAutoGeneratedFileName(cleaned))
          ? cleaned
          : copy.intakeTopicFallbackDocument;
    } else {
      topicLabel = copy.intakeTopicFallbackGeneric;
    }

    if (topicLabel.length > 72) {
      topicLabel = '${topicLabel.substring(0, 69)}…';
    }

    return SkulMateIntakeAnalysis(
      topicLabel: topicLabel,
      resolvedText: resolvedText,
      attachment: resolvedAttachment,
      contextSummary: contextSummary,
      uploadedFileUrls: uploadedFileUrls,
      uploadedFileNames: uploadedFileNames,
    );
  }

  static Future<
      ({
        String topicLabel,
        String? contextSummary,
        List<String>? uploadedFileUrls,
        List<String>? uploadedFileNames,
        SkulMateIntakeAttachment attachment,
      })> _analyzePhotoBundle(
    SkulMateIntakePayload payload,
    SkulMateCopy copy,
  ) async {
    final images = payload.images!;
    final paths = images
        .map((f) => f.path)
        .where((p) => p.isNotEmpty)
        .toList();
    final baseAttachment = SkulMateIntakeAttachment(
      source: SkulMateIntakeSource.photo,
      label: copy.photo,
      fileName: images.length == 1 ? images.first.name : '${images.length} photos',
      localImagePath: paths.isNotEmpty ? paths.first : null,
      localImagePaths: paths.isNotEmpty ? paths : null,
      imageCount: images.length,
    );

    if (payload.hasPreUploadedImages) {
      try {
        final understood = await SkulMateService.understandImages(
          fileUrls: payload.preUploadedFileUrls!,
          sourceFileNames: payload.preUploadedSourceNames,
        );
        final topic = understood.topicLabel.trim().isNotEmpty
            ? understood.topicLabel.trim()
            : copy.intakeTopicFallbackPhoto;
        final summary = understood.summary.trim().isNotEmpty
            ? copy.intakePhotoContextSummary(understood.summary.trim())
            : null;
        return (
          topicLabel: topic,
          contextSummary: summary,
          uploadedFileUrls: payload.preUploadedFileUrls,
          uploadedFileNames: payload.preUploadedSourceNames,
          attachment: baseAttachment,
        );
      } catch (e) {
        LogService.warning(
          '🎮 [skulMate] Pre-uploaded image understand skipped: $e',
        );
        return (
          topicLabel: copy.intakeTopicFallbackPhoto,
          contextSummary: null,
          uploadedFileUrls: payload.preUploadedFileUrls,
          uploadedFileNames: payload.preUploadedSourceNames,
          attachment: baseAttachment,
        );
      }
    }

    final user = SupabaseService.client.auth.currentUser;
    if (user == null) {
      return (
        topicLabel: copy.intakeTopicFallbackPhoto,
        contextSummary: null,
        uploadedFileUrls: null,
        uploadedFileNames: null,
        attachment: baseAttachment,
      );
    }

    final urls = <String>[];
    final names = <String>[];

    try {
      LogService.info(
        '🎮 [skulMate] Uploading ${images.length} photo(s) for intake preview…',
      );
      for (var i = 0; i < images.length; i++) {
        final url = await StorageService.uploadDocument(
          userId: user.id,
          documentFile: images[i],
          documentType: 'skulmate_notes',
        );
        urls.add(url);
        names.add(images[i].name);
      }

      final understood = await SkulMateService.understandImages(
        fileUrls: urls,
        sourceFileNames: names,
      );

      final topic = understood.topicLabel.trim().isNotEmpty
          ? understood.topicLabel.trim()
          : copy.intakeTopicFallbackPhoto;
      final summary = understood.summary.trim().isNotEmpty
          ? copy.intakePhotoContextSummary(understood.summary.trim())
          : null;

      return (
        topicLabel: topic,
        contextSummary: summary,
        uploadedFileUrls: urls,
        uploadedFileNames: names,
        attachment: baseAttachment,
      );
    } catch (e) {
      LogService.warning(
        '🎮 [skulMate] Photo bundle understand skipped: $e',
      );
      return (
        topicLabel: copy.intakeTopicFallbackPhoto,
        contextSummary: null,
        uploadedFileUrls: urls.isNotEmpty ? urls : null,
        uploadedFileNames: names.isNotEmpty ? names : null,
        attachment: baseAttachment,
      );
    }
  }

  static SkulMateIntakeAttachment _attachmentFor(
    SkulMateIntakePayload payload,
    SkulMateCopy copy,
  ) {
    if (payload.hasYoutube) {
      final id = _youtubeVideoId(payload.youtubeUrl!);
      return SkulMateIntakeAttachment(
        source: SkulMateIntakeSource.youtube,
        label: copy.youtube,
        thumbnailUrl: id != null
            ? 'https://img.youtube.com/vi/$id/hqdefault.jpg'
            : null,
      );
    }
    if (payload.hasImages) {
      final images = payload.images!;
      final paths = images
          .map((f) => f.path)
          .where((p) => p.isNotEmpty)
          .toList();
      return SkulMateIntakeAttachment(
        source: SkulMateIntakeSource.photo,
        label: copy.photo,
        fileName: images.length == 1
            ? images.first.name
            : '${images.length} photos',
        localImagePath: paths.isNotEmpty ? paths.first : null,
        localImagePaths: paths.isNotEmpty ? paths : null,
        imageCount: images.length,
      );
    }
    if (payload.hasFiles || payload.filesWeb != null) {
      final name = _fileName(payload);
      final ext = name?.split('.').last.toLowerCase() ?? '';
      final label = ext == 'pdf'
          ? 'PDF'
          : ext == 'pptx' || ext == 'ppt'
              ? 'PowerPoint'
              : copy.upload;
      return SkulMateIntakeAttachment(
        source: SkulMateIntakeSource.document,
        label: label,
        fileName: name,
      );
    }
    if (payload.source == SkulMateIntakeSource.lecture) {
      return SkulMateIntakeAttachment(
        source: SkulMateIntakeSource.lecture,
        label: copy.recordLecture,
      );
    }
    if (payload.source == SkulMateIntakeSource.paste) {
      return SkulMateIntakeAttachment(
        source: SkulMateIntakeSource.paste,
        label: copy.paste,
      );
    }
    if (payload.hasTopicOnly || payload.source == SkulMateIntakeSource.typedTopic) {
      return SkulMateIntakeAttachment(
        source: SkulMateIntakeSource.typedTopic,
        label: payload.topicHint?.trim().isNotEmpty == true
            ? payload.topicHint!.trim()
            : copy.intakeTopicChip,
      );
    }
    return SkulMateIntakeAttachment(
      source: payload.source,
      label: copy.upload,
    );
  }

  static String? _fileName(SkulMateIntakePayload payload) {
    if (payload.filesWeb != null && payload.filesWeb!.isNotEmpty) {
      return payload.filesWeb!.first.name;
    }
    if (payload.files != null && payload.files!.isNotEmpty) {
      final path = payload.files!.first.path;
      return path.split('/').last;
    }
    if (payload.images != null && payload.images!.isNotEmpty) {
      return payload.images!.first.name;
    }
    return null;
  }

  static String? _cleanFileName(String? name) {
    if (name == null || name.trim().isEmpty) return null;
    var base = name.replaceAll(RegExp(r'\.[^.]+$'), '');
    base = base.replaceAll(RegExp(r'[-_]'), ' ').trim();
    return base.isEmpty ? null : base;
  }

  /// Camera/gallery picks often use opaque names like scaled_<uuid>.jpg.
  static bool _isAutoGeneratedFileName(String name) {
    final base = name.trim().toLowerCase();
    if (base.isEmpty) return true;
    if (base.startsWith('scaled_')) return true;
    if (RegExp(r'^[a-f0-9-]{20,}(\.(jpg|jpeg|png|heic|webp))?$').hasMatch(base)) {
      return true;
    }
    if (RegExp(r'^\d+_notes\.txt$').hasMatch(base)) return true;
    return false;
  }

  static String? _topicFromText(String? text) {
    if (text == null || text.trim().isEmpty) return null;
    final lines = text
        .split(RegExp(r'\n+'))
        .map((l) => l.trim())
        .where((l) => l.length > 2)
        .toList();
    if (lines.isEmpty) return null;
    final first = lines.first;
    if (first.length <= 80) return first;
    return '${first.substring(0, 77)}…';
  }

  static String? _youtubeVideoId(String url) {
    final uri = Uri.tryParse(url.trim());
    if (uri == null) return null;
    if (uri.host.contains('youtu.be') && uri.pathSegments.isNotEmpty) {
      return uri.pathSegments.first;
    }
    final v = uri.queryParameters['v'];
    if (v != null && v.isNotEmpty) return v;
    return null;
  }
}
